# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: RELEASE Build

on:
  workflow_dispatch

jobs:
  macos:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Eclipse Temurin OpenJDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build macOS natives
        run: |
          /usr/bin/xcodebuild -version
          ./gradlew fetchDependencies
          ./gradlew jnigen jnigenBuildAllIOS jnigenBuildAllMacOsX
      - name: Upload macOS/iOS natives
        uses: actions/upload-artifact@v4.4.0
        with:
          name: macos-natives
          path: build/jnigen/libs

  linux:
    needs: macos
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Eclipse Temurin OpenJDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - run: echo "http://ports.ubuntu.com/ubuntu-ports" | sudo tee -a /etc/apt/apt-mirrors.txt
      - name: Add extra platform architectures
        run: sudo dpkg --add-architecture i386; sudo dpkg --add-architecture armhf; sudo dpkg --add-architecture arm64
      - run: sudo apt-get update || true
      - name: Install Windows compilers
        run: sudo apt-get -yq install g++-mingw-w64-i686 g++-mingw-w64-x86-64
      - name: Install Linux cross-compilation toolchains
        run: |
          sudo apt-get -yq install gcc g++ gcc-multilib g++-multilib
          sudo apt-get -yq install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
          sudo apt-get -yq install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf binutils-arm-linux-gnueabihf
          sudo apt-get -yq install gcc-riscv64-linux-gnu g++-riscv64-linux-gnu libc6-dev-riscv64-cross
      - name: Download macOS/iOS natives
        uses: actions/download-artifact@v4.1.8
        with:
          name: macos-natives
          path: build/jnigen/libs
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -O android-ndk.zip
          echo "769ee342ea75f80619d985c2da990c48b3d8eaf45f48783a2d48870d04b46108  android-ndk.zip" | sha256sum --check
          unzip android-ndk.zip
          echo "NDK_HOME=$(pwd)/android-ndk-r25c" >> $GITHUB_ENV
      - name: Build with Gradle
        run: |
          ./gradlew fetchDependencies
          ./gradlew jnigen jnigenBuildAllLinux jnigenBuildAllWindows jnigenBuildAllAndroid
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Release build deploy
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew publish -PRELEASE=true -Psigning.gnupg.keyId=${{ secrets.GPG_KEYID }} -Psigning.gnupg.passphrase=${{ secrets.GPG_PASSPHRASE }} -Psigning.gnupg.keyName=${{ secrets.GPG_KEYID }}
      - name: Upload all output libs
        uses: actions/upload-artifact@v4.4.0
        with:
          name: output-libs
          path: build/jnigen/libs
      - name: Trigger manual upload to Central Repository
        run: |
          curl -X POST \
            -H "Authorization: Bearer $(echo -n '${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}' | base64)" \
            -H "Content-Type: application/json" \
            https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/games.rednblack